name: Publish Quarto Site

on:
  push:
    branches:
      - main  # Rama que activa la publicación

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and publish
        run: |
          quarto publish quarto-pub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
